# Urban Heat Island (UHI) Benchmark Notebook

## Load In Dependencies

In [1]:
# Supress Warnings
import warnings
warnings.filterwarnings('ignore')

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Data Science
import numpy as np
import pandas as pd

# Multi-dimensional arrays and datasets
import xarray as xr

# Geospatial raster data handling
import rioxarray as rxr

# Geospatial data analysis
import geopandas as gpd

# Geospatial operations
import rasterio
from rasterio import windows  
from rasterio import features  
from rasterio import warp
from rasterio.warp import transform_bounds 
from rasterio.windows import from_bounds 

# Image Processing
from PIL import Image

# Coordinate transformations
from pyproj import Proj, Transformer, CRS

# Feature Engineering
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# Machine Learning
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

# Planetary Computer Tools
import pystac_client
import planetary_computer as pc
from pystac.extensions.eo import EOExtension as eo

# Others
import os
from tqdm import tqdm

In [2]:
# Load the training data from csv file and display the first few rows to inspect the data
ground_df = pd.read_csv("DB_Training_data_uhi_index_2025-02-18.csv")
ground_df.head()

   Longitude   Latitude          datetime  UHI Index
0 -73.909167  40.813107  24-07-2021 15:53   1.030289
1 -73.909187  40.813045  24-07-2021 15:53   1.030289
2 -73.909215  40.812978  24-07-2021 15:53   1.023798
3 -73.909242  40.812908  24-07-2021 15:53   1.023798
4 -73.909257  40.812845  24-07-2021 15:53   1.021634

In [3]:
# Extract average satellite band values in a focal buffer

def extract_focal_buffer(tiff_path, csv_path, buffer_size):
    
    # Load the GeoTIFF data
    data = rxr.open_rasterio(tiff_path)
    tiff_crs = data.rio.crs
    
    # Read the Excel file using pandas
    df = pd.read_csv(csv_path)
    latitudes = df['Latitude'].values
    longitudes = df['Longitude'].values

    # 3. Convert lat/long to the GeoTIFF's CRS
    # Create a Proj object for EPSG:4326 (WGS84 - lat/long) and the GeoTIFF's CRS
    proj_wgs84 = Proj(init='epsg:4326')  # EPSG:4326 is the common lat/long CRS
    proj_tiff = Proj(tiff_crs)
    
    # Create a transformer object
    transformer = Transformer.from_proj(proj_wgs84, proj_tiff)

    # B01_values = []
    B02_values = []
    B03_values = []
    B04_values = []
    B05_values = []
    B06_values = []
    B07_values = []
    B08_values = []
    B8A_values = []
    # B09_values = []
    B11_values = []
    B12_values = []


# Iterate over the latitudes and longitudes, and extract the corresponding mean band values in a the buffer zone
    for lat, lon in tqdm(zip(latitudes, longitudes), total=len(latitudes), desc="Mapping values"):
    # Assuming the correct dimensions are 'y' and 'x' (replace these with actual names from data.coords)
    
        # B01_value = data.sel(
        #     x=slice(lon - buffer_size/111320, lon + buffer_size/111320),
        #     y=slice(lat + buffer_size/111320, lat - buffer_size/111320),  
        #     band=1).values
        # B01_value_mean = B01_value.mean()
        # B01_values.append(B01_value_mean)

        B02_value = data.sel(
        x=slice(lon - buffer_size/111320, lon + buffer_size/111320),
        y=slice(lat + buffer_size/111320, lat - buffer_size/111320),  
        band=2).values
        B02_value_mean = B02_value.mean()
        B02_values.append(B02_value_mean)

        B03_value = data.sel(
        x=slice(lon - buffer_size/111320, lon + buffer_size/111320),
        y=slice(lat + buffer_size/111320, lat - buffer_size/111320),  
        band=3).values
        B03_value_mean = B03_value.mean()
        B03_values.append(B03_value_mean)

        B04_value = data.sel(
            x=slice(lon - buffer_size/111320, lon + buffer_size/111320),
            y=slice(lat + buffer_size/111320, lat - buffer_size/111320),  
            band=4).values
        B04_value_mean = B04_value.mean()
        B04_values.append(B04_value_mean)

        B05_value = data.sel(
            x=slice(lon - buffer_size/111320, lon + buffer_size/111320),
            y=slice(lat + buffer_size/111320, lat - buffer_size/111320),  
            band=5).values
        B05_value_mean = B05_value.mean()
        B05_values.append(B05_value_mean)

        B06_value = data.sel(
            x=slice(lon - buffer_size/111320, lon + buffer_size/111320),
            y=slice(lat + buffer_size/111320, lat - buffer_size/111320),  
            band=6).values
        B06_value_mean = B06_value.mean()
        B06_values.append(B06_value_mean)

        B07_value = data.sel(
            x=slice(lon - buffer_size/111320, lon + buffer_size/111320),
            y=slice(lat + buffer_size/111320, lat - buffer_size/111320),  
            band=7).values
        B07_value_mean = B07_value.mean()
        B07_values.append(B07_value_mean)

        B08_value = data.sel(
            x=slice(lon - buffer_size/111320, lon + buffer_size/111320),
            y=slice(lat + buffer_size/111320, lat - buffer_size/111320),  
            band=8).values
        B08_value_mean = B08_value.mean()
        B08_values.append(B08_value_mean)

        B8A_value = data.sel(
            x=slice(lon - buffer_size/111320, lon + buffer_size/111320),
            y=slice(lat + buffer_size/111320, lat - buffer_size/111320),  
            band=9).values
        B8A_value_mean = B8A_value.mean()
        B8A_values.append(B8A_value_mean)

        # B09_value = data.sel(
        #     x=slice(lon - buffer_size/111320, lon + buffer_size/111320),
        #     y=slice(lat + buffer_size/111320, lat - buffer_size/111320),  
        #     band=10).values
        # B09_value_mean = B09_value.mean()
        # B09_values.append(B09_value_mean)
        
        B11_value = data.sel(
            x=slice(lon - buffer_size/111320, lon + buffer_size/111320),
            y=slice(lat + buffer_size/111320, lat - buffer_size/111320),  
            band=11).values
        B11_value_mean = B11_value.mean()
        B11_values.append(B11_value_mean)

        B12_value = data.sel(
            x=slice(lon - buffer_size/111320, lon + buffer_size/111320),
            y=slice(lat + buffer_size/111320, lat - buffer_size/111320),  
            band=12).values
        B12_value_mean = B12_value.mean()
        B12_values.append(B12_value_mean)
    

    # Create a DataFrame to store the band values
    df = pd.DataFrame()
    # df[f'B01_{buffer_size}'] = B01_values
    df[f'B02_{buffer_size}'] = B02_values
    df[f'B03_{buffer_size}'] = B03_values
    df[f'B04_{buffer_size}'] = B04_values
    df[f'B05_{buffer_size}'] = B05_values
    df[f'B06_{buffer_size}'] = B06_values
    df[f'B07_{buffer_size}'] = B07_values
    df[f'B08_{buffer_size}'] = B08_values
    df[f'B8A_{buffer_size}'] = B8A_values
    # df[f'B09_{buffer_size}'] = B09_values
    df[f'B11_{buffer_size}'] = B11_values
    df[f'B12_{buffer_size}'] = B12_values
    
    return df

In [4]:
# # Extract the mean band values in the focal buffer and store in a data frame.

# big_data = pd.DataFrame()

# for i in range(50, 1001, 50):
#     focal_data = extract_focal_buffer('v1_S2.tiff', 'DB_Training_data_uhi_index_2025-02-18.csv',i)
#     big_data = pd.concat([big_data, focal_data], axis=1)

# big_data.head()

In [5]:
# # Make a copy of big_data, calculate gNDVI and NDBI and add them as columns in big_data

# big_data_indices = big_data.copy()

# for i in range(50, 1001, 50):
#     big_data_indices[f'NDVI_{i}'] = (big_data_indices[f'B08_{i}'] - big_data_indices[f'B04_{i}']) / (big_data_indices[f'B08_{i}'] + big_data_indices[f'B04_{i}'])
#     big_data_indices[f'NDVI_{i}'] = big_data_indices[f'NDVI_{i}'].replace([np.inf, -np.inf], np.nan)

# # for i in range(50, 1001, 50):
# #     big_data_indices[f'gNDVI_{i}'] = (big_data_indices[f'B08_{i}'] - big_data_indices[f'B03_{i}']) / (big_data_indices[f'B08_{i}'] + big_data_indices[f'B03_{i}'])
# #     big_data_indices[f'gNDVI_{i}'] = big_data_indices[f'gNDVI_{i}'].replace([np.inf, -np.inf], np.nan)

# for i in range(50, 1001, 50):
#     big_data_indices[f'NDBI_{i}'] = (big_data_indices[f'B11_{i}'] - big_data_indices[f'B08_{i}']) / (big_data_indices[f'B11_{i}'] + big_data_indices[f'B08_{i}'])
#     big_data_indices[f'NDBI_{i}'] = big_data_indices[f'NDBI_{i}'].replace([np.inf, -np.inf], np.nan)

# big_data_indices.head()

In [6]:
# big_data_indices.to_csv("big_data_indices.csv", index=False)

In [7]:
big_data_indices = pd.read_csv("big_data_indices.csv")

In [8]:
# Download the building footprint data and view it.

building_df = pd.read_csv("building_df.csv")
building_df.head()

,Longitude,Latitude,building_count_50,building_count_100,building_count_150,building_count_200,building_count_250,building_count_300,building_count_350,building_count_400,...,building_count_550,building_count_600,building_count_650,building_count_700,building_count_750,building_count_800,building_count_850,building_count_900,building_count_950,building_count_1000
0,-73.909167,40.813107,1,4,6,11,13,26,37,56,...,108,125,145,159,177,190,211,238,271,298
1,-73.909187,40.813045,1,4,6,11,16,26,38,53,...,112,126,145,157,174,188,208,234,267,293
2,-73.909215,40.812978,1,3,6,11,21,26,39,48,...,106,124,144,155,171,185,211,234,269,295
3,-73.909242,40.812908,1,3,5,10,22,29,39,45,...,107,125,143,156,170,186,206,231,269,295
4,-73.909257,40.812845,1,2,5,11,21,30,38,46,...,106,127,143,156,170,186,202,231,264,294

In [9]:
# Double check the latitude and longitude columns between the data frames are equal.

long_isequal = ground_df["Longitude"].equals(building_df["Longitude"])
print(long_isequal)
lat_isequal = ground_df["Latitude"].equals(building_df["Latitude"])
print(lat_isequal)

True
True

In [11]:
# SInce the above returned is "True", join big_data2 and the building footprint data.
big_data2 = big_data_indices.copy()
big_data2 = pd.concat([building_df, big_data2], axis=1)
big_data2.head()

,Longitude,Latitude,building_count_50,building_count_100,building_count_150,building_count_200,building_count_250,building_count_300,building_count_350,building_count_400,...,NDBI_550,NDBI_600,NDBI_650,NDBI_700,NDBI_750,NDBI_800,NDBI_850,NDBI_900,NDBI_950,NDBI_1000
0,-73.909167,40.813107,1,4,6,11,13,26,37,56,...,-0.026093,-0.020387,-0.014609,-0.009561,-0.005145,-0.000029,0.003311,0.005167,0.008583,0.010840
1,-73.909187,40.813045,1,4,6,11,16,26,38,53,...,-0.025319,-0.020251,-0.014864,-0.009199,-0.004633,0.000500,0.003927,0.005769,0.008846,0.011128
2,-73.909215,40.812978,1,3,6,11,21,26,39,48,...,-0.024974,-0.020282,-0.014713,-0.008867,-0.004486,0.000982,0.004244,0.006142,0.009054,0.011226
3,-73.909242,40.812908,1,3,5,10,22,29,39,45,...,-0.025165,-0.020333,-0.015249,-0.009345,-0.004260,0.001088,0.004404,0.006463,0.009294,0.011332
4,-73.909257,40.812845,1,2,5,11,21,30,38,46,...,-0.024276,-0.019959,-0.015115,-0.009349,-0.004319,0.001139,0.004664,0.006765,0.009167,0.011160

In [12]:
# Read the canopy height data and double check longitudes and latitudes are the same.

canopy_df = pd.read_csv("canopy_df.csv")
long_isequal = ground_df["Longitude"].equals(canopy_df["Longitude"])
print(long_isequal)
lat_isequal = ground_df["Latitude"].equals(canopy_df["Latitude"])
print(lat_isequal)
canopy_df.head()

True
True

   Longitude   Latitude          datetime  UHI Index  canopy_height
0 -73.909167  40.813107  24-07-2021 15:53   1.030289       6.184643
1 -73.909187  40.813045  24-07-2021 15:53   1.030289       6.184643
2 -73.909215  40.812978  24-07-2021 15:53   1.023798       6.184643
3 -73.909242  40.812908  24-07-2021 15:53   1.023798       6.184643
4 -73.909257  40.812845  24-07-2021 15:53   1.021634       6.184643

In [13]:
# Add the canopy height data to the main data frame.

big_data2["canopy_height"] = canopy_df["canopy_height"]
big_data2["UHI Index"] = ground_df["UHI Index"]
big_data2.head()

,Longitude,Latitude,building_count_50,building_count_100,building_count_150,building_count_200,building_count_250,building_count_300,building_count_350,building_count_400,...,NDBI_650,NDBI_700,NDBI_750,NDBI_800,NDBI_850,NDBI_900,NDBI_950,NDBI_1000,canopy_height,UHI Index
0,-73.909167,40.813107,1,4,6,11,13,26,37,56,...,-0.014609,-0.009561,-0.005145,-0.000029,0.003311,0.005167,0.008583,0.010840,6.184643,1.030289
1,-73.909187,40.813045,1,4,6,11,16,26,38,53,...,-0.014864,-0.009199,-0.004633,0.000500,0.003927,0.005769,0.008846,0.011128,6.184643,1.030289
2,-73.909215,40.812978,1,3,6,11,21,26,39,48,...,-0.014713,-0.008867,-0.004486,0.000982,0.004244,0.006142,0.009054,0.011226,6.184643,1.023798
3,-73.909242,40.812908,1,3,5,10,22,29,39,45,...,-0.015249,-0.009345,-0.004260,0.001088,0.004404,0.006463,0.009294,0.011332,6.184643,1.023798
4,-73.909257,40.812845,1,2,5,11,21,30,38,46,...,-0.015115,-0.009349,-0.004319,0.001139,0.004664,0.006765,0.009167,0.011160,6.184643,1.021634

## Remove duplicates

In [14]:
# Make a copy of big_data2 for modelling purposes.

uhi_data = big_data2.copy()

In [15]:
print(list(uhi_data.columns[2:-1]))

['building_count_50', 'building_count_100', 'building_count_150', 'building_count_200', 'building_count_250', 'building_count_300', 'building_count_350', 'building_count_400', 'building_count_450', 'building_count_500', 'building_count_550', 'building_count_600', 'building_count_650', 'building_count_700', 'building_count_750', 'building_count_800', 'building_count_850', 'building_count_900', 'building_count_950', 'building_count_1000', 'B02_50', 'B03_50', 'B04_50', 'B05_50', 'B06_50', 'B07_50', 'B08_50', 'B8A_50', 'B11_50', 'B12_50', 'B02_100', 'B03_100', 'B04_100', 'B05_100', 'B06_100', 'B07_100', 'B08_100', 'B8A_100', 'B11_100', 'B12_100', 'B02_150', 'B03_150', 'B04_150', 'B05_150', 'B06_150', 'B07_150', 'B08_150', 'B8A_150', 'B11_150', 'B12_150', 'B02_200', 'B03_200', 'B04_200', 'B05_200', 'B06_200', 'B07_200', 'B08_200', 'B8A_200', 'B11_200', 'B12_200', 'B02_250', 'B03_250', 'B04_250', 'B05_250', 'B06_250', 'B07_250', 'B08_250', 'B8A_250', 'B11_250', 'B12_250', 'B02_300', 'B03_300', 'B04_300', 'B05_300', 'B06_300', 'B07_300', 'B08_300', 'B8A_300', 'B11_300', 'B12_300', 'B02_350', 'B03_350', 'B04_350', 'B05_350', 'B06_350', 'B07_350', 'B08_350', 'B8A_350', 'B11_350', 'B12_350', 'B02_400', 'B03_400', 'B04_400', 'B05_400', 'B06_400', 'B07_400', 'B08_400', 'B8A_400', 'B11_400', 'B12_400', 'B02_450', 'B03_450', 'B04_450', 'B05_450', 'B06_450', 'B07_450', 'B08_450', 'B8A_450', 'B11_450', 'B12_450', 'B02_500', 'B03_500', 'B04_500', 'B05_500', 'B06_500', 'B07_500', 'B08_500', 'B8A_500', 'B11_500', 'B12_500', 'B02_550', 'B03_550', 'B04_550', 'B05_550', 'B06_550', 'B07_550', 'B08_550', 'B8A_550', 'B11_550', 'B12_550', 'B02_600', 'B03_600', 'B04_600', 'B05_600', 'B06_600', 'B07_600', 'B08_600', 'B8A_600', 'B11_600', 'B12_600', 'B02_650', 'B03_650', 'B04_650', 'B05_650', 'B06_650', 'B07_650', 'B08_650', 'B8A_650', 'B11_650', 'B12_650', 'B02_700', 'B03_700', 'B04_700', 'B05_700', 'B06_700', 'B07_700', 'B08_700', 'B8A_700', 'B11_700', 'B12_700', 'B02_750', 'B03_750', 'B04_750', 'B05_750', 'B06_750', 'B07_750', 'B08_750', 'B8A_750', 'B11_750', 'B12_750', 'B02_800', 'B03_800', 'B04_800', 'B05_800', 'B06_800', 'B07_800', 'B08_800', 'B8A_800', 'B11_800', 'B12_800', 'B02_850', 'B03_850', 'B04_850', 'B05_850', 'B06_850', 'B07_850', 'B08_850', 'B8A_850', 'B11_850', 'B12_850', 'B02_900', 'B03_900', 'B04_900', 'B05_900', 'B06_900', 'B07_900', 'B08_900', 'B8A_900', 'B11_900', 'B12_900', 'B02_950', 'B03_950', 'B04_950', 'B05_950', 'B06_950', 'B07_950', 'B08_950', 'B8A_950', 'B11_950', 'B12_950', 'B02_1000', 'B03_1000', 'B04_1000', 'B05_1000', 'B06_1000', 'B07_1000', 'B08_1000', 'B8A_1000', 'B11_1000', 'B12_1000', 'NDVI_50', 'NDVI_100', 'NDVI_150', 'NDVI_200', 'NDVI_250', 'NDVI_300', 'NDVI_350', 'NDVI_400', 'NDVI_450', 'NDVI_500', 'NDVI_550', 'NDVI_600', 'NDVI_650', 'NDVI_700', 'NDVI_750', 'NDVI_800', 'NDVI_850', 'NDVI_900', 'NDVI_950', 'NDVI_1000', 'NDBI_50', 'NDBI_100', 'NDBI_150', 'NDBI_200', 'NDBI_250', 'NDBI_300', 'NDBI_350', 'NDBI_400', 'NDBI_450', 'NDBI_500', 'NDBI_550', 'NDBI_600', 'NDBI_650', 'NDBI_700', 'NDBI_750', 'NDBI_800', 'NDBI_850', 'NDBI_900', 'NDBI_950', 'NDBI_1000', 'canopy_height']

In [16]:
# Remove duplicate rows from the DataFrame based on specified columns and keep the first occurrence

columns_to_check = (list(uhi_data.columns[2:-1]))
for col in columns_to_check:
    # Check if the value is a numpy array and has more than one dimension
    uhi_data[col] = uhi_data[col].apply(lambda x: tuple(x) if isinstance(x, np.ndarray) and x.ndim > 0 else x)

# Now remove duplicates
uhi_data = uhi_data.drop_duplicates(subset=columns_to_check, keep='first')
uhi_data.shape

(11224, 264)

In [17]:
# Resetting the index of the dataset

uhi_data=uhi_data.reset_index(drop=True)

## Model Building

In [18]:
# Exclude the latitude and longitude columns

uhi_data = uhi_data.drop(columns=['Longitude', 'Latitude'])
uhi_data.head()

,building_count_50,building_count_100,building_count_150,building_count_200,building_count_250,building_count_300,building_count_350,building_count_400,building_count_450,building_count_500,...,NDBI_650,NDBI_700,NDBI_750,NDBI_800,NDBI_850,NDBI_900,NDBI_950,NDBI_1000,canopy_height,UHI Index
0,1,4,6,11,13,26,37,56,71,86,...,-0.014609,-0.009561,-0.005145,-0.000029,0.003311,0.005167,0.008583,0.010840,6.184643,1.030289
1,1,4,6,11,16,26,38,53,70,85,...,-0.014864,-0.009199,-0.004633,0.000500,0.003927,0.005769,0.008846,0.011128,6.184643,1.030289
2,1,3,6,11,21,26,39,48,70,87,...,-0.014713,-0.008867,-0.004486,0.000982,0.004244,0.006142,0.009054,0.011226,6.184643,1.023798
3,1,3,5,10,22,29,39,45,68,88,...,-0.015249,-0.009345,-0.004260,0.001088,0.004404,0.006463,0.009294,0.011332,6.184643,1.023798
4,1,2,5,11,21,30,38,46,65,88,...,-0.015115,-0.009349,-0.004319,0.001139,0.004664,0.006765,0.009167,0.011160,6.184643,1.021634

### Train and Test Split

In [19]:
# Split the data into features (X) and target (y), and then into training and testing sets

X = uhi_data.drop(columns=['UHI Index'])
y = uhi_data ['UHI Index']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,random_state=123)

### Feature Scaling

In [20]:
# Scale the training and test data using standardscaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

### Model Training

In [21]:
# Train the Random Forest model on the training data

model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train,y_train)

RandomForestRegressor(random_state=42)

## Model Evaluation

### In-Sample Evaluation

In [22]:
# Make predictions on the training data

insample_predictions = model.predict(X_train)

In [23]:
# calculate R-squared score for in-sample predictions

Y_train = y_train.tolist()
r2_score(Y_train, insample_predictions)

0.9941625869962237

### Out-Sample Evaluation

In [24]:
# Make predictions on the test data

outsample_predictions = model.predict(X_test)

In [25]:
# calculate R-squared score for out-sample predictions

Y_test = y_test.tolist()
r2_score(Y_test, outsample_predictions)

0.9626707112316802

In [26]:
# Examine importances of features used in the model.

importances = model.feature_importances_

columns_list = list(uhi_data.columns[:-1])
feature_importance = pd.DataFrame()
feature_importance["features"] = columns_list
feature_importance["importance"] = importances
feature_importance = feature_importance.sort_values(by='importance', ascending=False)
print(feature_importance.head(20))

                features  importance
181              B03_850    0.187064
189              B12_850    0.046553
19   building_count_1000    0.026823
260        canopy_height    0.025868
221             NDVI_100    0.021769
209              B12_950    0.019583
193              B05_900    0.018444
191              B03_900    0.017709
194              B06_900    0.014145
211             B03_1000    0.012711
213             B05_1000    0.010715
214             B06_1000    0.010577
210             B02_1000    0.010050
108              B11_450    0.008835
223             NDVI_200    0.008754
90               B02_400    0.008694
183              B05_850    0.008054
18    building_count_950    0.007927
212             B04_1000    0.007376
229             NDVI_500    0.006660

## Submission

In [27]:
#Reading the coordinates for the submission

test_file = pd.read_csv('DB_Submission_template.csv')
test_file.head()

   Longitude   Latitude  UHI Index
0 -73.971665  40.788763        NaN
1 -73.971928  40.788875        NaN
2 -73.967080  40.789080        NaN
3 -73.972550  40.789082        NaN
4 -73.969697  40.787953        NaN

In [28]:
# Mapping satellite data for submission.

val_focaldata_total = pd.DataFrame()

for i in range(50, 1001, 50):
    val_focaldata = extract_focal_buffer('v1_S2.tiff', 'DB_Submission_template.csv',i)
    val_focaldata_total = pd.concat([val_focaldata_total, val_focaldata], axis=1)

val_focaldata_total.head()

Mapping values: 100%|█████████████████████████████████████████████████████████████| 1040/1040 [00:06<00:00, 158.18it/s]
Mapping values: 100%|█████████████████████████████████████████████████████████████| 1040/1040 [00:07<00:00, 148.40it/s]
Mapping values: 100%|█████████████████████████████████████████████████████████████| 1040/1040 [00:06<00:00, 171.54it/s]
Mapping values: 100%|█████████████████████████████████████████████████████████████| 1040/1040 [00:06<00:00, 172.82it/s]
Mapping values: 100%|█████████████████████████████████████████████████████████████| 1040/1040 [00:06<00:00, 164.29it/s]
Mapping values: 100%|█████████████████████████████████████████████████████████████| 1040/1040 [00:06<00:00, 165.97it/s]
Mapping values: 100%|█████████████████████████████████████████████████████████████| 1040/1040 [00:06<00:00, 165.89it/s]
Mapping values: 100%|█████████████████████████████████████████████████████████████| 1040/1040 [00:06<00:00, 163.21it/s]
Mapping values: 100%|█████████████████████████████████████████████████████████████| 1040/1040 [00:06<00:00, 165.24it/s]
Mapping values: 100%|█████████████████████████████████████████████████████████████| 1040/1040 [00:06<00:00, 162.33it/s]
Mapping values: 100%|█████████████████████████████████████████████████████████████| 1040/1040 [00:06<00:00, 161.27it/s]
Mapping values: 100%|█████████████████████████████████████████████████████████████| 1040/1040 [00:06<00:00, 159.50it/s]
Mapping values: 100%|█████████████████████████████████████████████████████████████| 1040/1040 [00:06<00:00, 149.92it/s]
Mapping values: 100%|█████████████████████████████████████████████████████████████| 1040/1040 [00:07<00:00, 146.42it/s]
Mapping values: 100%|█████████████████████████████████████████████████████████████| 1040/1040 [00:07<00:00, 144.60it/s]
Mapping values: 100%|█████████████████████████████████████████████████████████████| 1040/1040 [00:07<00:00, 140.71it/s]
Mapping values: 100%|█████████████████████████████████████████████████████████████| 1040/1040 [00:07<00:00, 136.59it/s]
Mapping values: 100%|█████████████████████████████████████████████████████████████| 1040/1040 [00:08<00:00, 128.84it/s]
Mapping values: 100%|█████████████████████████████████████████████████████████████| 1040/1040 [00:07<00:00, 132.74it/s]
Mapping values: 100%|█████████████████████████████████████████████████████████████| 1040/1040 [00:07<00:00, 131.30it/s]

,B02_50,B03_50,B04_50,B05_50,B06_50,B07_50,B08_50,B8A_50,B11_50,B12_50,...,B02_1000,B03_1000,B04_1000,B05_1000,B06_1000,B07_1000,B08_1000,B8A_1000,B11_1000,B12_1000
0,788.310,925.185,875.970,1273.675,2247.440,2536.895,2577.22,2659.30,1950.540,1416.585,...,978.012650,1099.278700,1095.363513,1333.587050,1969.310100,2214.127025,2200.999550,2300.116187,1874.395113,1459.679738
1,1038.935,1187.740,1164.255,1518.495,2406.525,2685.725,2728.24,2778.34,2110.570,1579.765,...,981.590288,1103.161063,1100.901575,1336.973737,1963.311625,2205.005575,2191.656338,2289.659187,1871.731850,1460.342238
2,1160.615,1282.075,1376.650,1518.435,1753.855,1871.780,1826.27,1928.77,1944.415,1705.410,...,870.376325,991.780575,953.654725,1212.963037,1971.004325,2261.677462,2257.506688,2367.270900,1792.507413,1330.793125
3,1570.805,1725.925,1872.340,2051.225,2301.925,2401.485,2359.35,2433.92,2520.260,2220.085,...,988.471288,1109.948725,1110.271262,1341.411263,1945.848750,2181.404762,2165.664975,2262.220087,1861.608487,1458.531088
4,1395.630,1488.150,1528.325,1676.825,2242.480,2485.355,2449.36,2525.06,2336.520,1933.050,...,939.889125,1061.437038,1041.545188,1292.410275,1992.930263,2261.517025,2253.487525,2357.972137,1859.527250,1418.919138

In [29]:
# Calculate indices and add them as columns

for i in range(50, 1001, 50):
    # val_focaldata_total[f'gNDVI_{i}'] = (val_focaldata_total[f'B11_{i}'] -  val_focaldata_total[f'B03_{i}']) / ( val_focaldata_total[f'B11_{i}'] +  val_focaldata_total[f'B11_{i}'])
    # val_focaldata_total[f'gNDVI_{i}'] =  val_focaldata_total[f'gNDVI_{i}'].replace([np.inf, -np.inf], np.nan)
    val_focaldata_total[f'NDVI_{i}'] = (val_focaldata_total[f'B08_{i}'] - val_focaldata_total[f'B04_{i}']) / (val_focaldata_total[f'B08_{i}'] + val_focaldata_total[f'B04_{i}'])
    val_focaldata_total[f'NDVI_{i}'] = val_focaldata_total[f'NDVI_{i}'].replace([np.inf, -np.inf], np.nan)
for i in range(50, 1001, 50):
    val_focaldata_total[f'NDBI_{i}'] = (val_focaldata_total[f'B11_{i}'] - val_focaldata_total[f'B08_{i}']) / (val_focaldata_total[f'B11_{i}'] + val_focaldata_total[f'B08_{i}'])
    val_focaldata_total[f'NDBI_{i}'] = val_focaldata_total[f'NDBI_{i}'].replace([np.inf, -np.inf], np.nan)

val_focaldata_total.head()

,B02_50,B03_50,B04_50,B05_50,B06_50,B07_50,B08_50,B8A_50,B11_50,B12_50,...,NDBI_550,NDBI_600,NDBI_650,NDBI_700,NDBI_750,NDBI_800,NDBI_850,NDBI_900,NDBI_950,NDBI_1000
0,788.310,925.185,875.970,1273.675,2247.440,2536.895,2577.22,2659.30,1950.540,1416.585,...,-0.013411,-0.022313,-0.030077,-0.038276,-0.048054,-0.057627,-0.064880,-0.070877,-0.076302,-0.080141
1,1038.935,1187.740,1164.255,1518.495,2406.525,2685.725,2728.24,2778.34,2110.570,1579.765,...,-0.008250,-0.019469,-0.028554,-0.036309,-0.045339,-0.054397,-0.061865,-0.068354,-0.073772,-0.078733
2,1160.615,1282.075,1376.650,1518.435,1753.855,1871.780,1826.27,1928.77,1944.415,1705.410,...,-0.098532,-0.098487,-0.097550,-0.097520,-0.100565,-0.106120,-0.109531,-0.112391,-0.113822,-0.114814
3,1570.805,1725.925,1872.340,2051.225,2301.925,2401.485,2359.35,2433.92,2520.260,2220.085,...,-0.001769,-0.013147,-0.023052,-0.031462,-0.039962,-0.048880,-0.055788,-0.062316,-0.068673,-0.075499
4,1395.630,1488.150,1528.325,1676.825,2242.480,2485.355,2449.36,2525.06,2336.520,1933.050,...,-0.058645,-0.062678,-0.069504,-0.076383,-0.079686,-0.081898,-0.085792,-0.090658,-0.093918,-0.095784

In [30]:
# Read the building footprint data applicable for the test data.

test_building_df = pd.read_csv("test_building_df.csv")
test_building_df.head()

,Longitude,Latitude,building_count_50,building_count_100,building_count_150,building_count_200,building_count_250,building_count_300,building_count_350,building_count_400,...,building_count_550,building_count_600,building_count_650,building_count_700,building_count_750,building_count_800,building_count_850,building_count_900,building_count_950,building_count_1000
0,-73.971665,40.788763,2,4,8,13,14,24,26,38,...,55,66,73,85,97,105,119,132,145,162
1,-73.971928,40.788875,2,5,6,9,15,21,34,36,...,58,66,75,85,96,108,121,134,149,165
2,-73.967080,40.789080,1,3,3,4,5,5,8,12,...,29,37,41,48,52,64,68,78,85,97
3,-73.972550,40.789082,2,5,6,11,16,23,30,39,...,61,66,78,88,100,114,129,141,157,174
4,-73.969697,40.787953,2,2,4,5,6,13,16,21,...,39,45,50,56,70,77,89,100,112,121

In [31]:
# Check the latitude and longitude columns between the data frames are the same.

long_isequal = test_file["Longitude"].equals(test_building_df["Longitude"])
print(long_isequal)
lat_isequal = test_file["Latitude"].equals(test_building_df["Latitude"])
print(lat_isequal)

True
True

In [32]:
# Since the above returned was true, join the data frames.

val_focaldata_total = pd.concat([test_building_df, val_focaldata_total], axis=1)
val_focaldata_total.head()

,Longitude,Latitude,building_count_50,building_count_100,building_count_150,building_count_200,building_count_250,building_count_300,building_count_350,building_count_400,...,NDBI_550,NDBI_600,NDBI_650,NDBI_700,NDBI_750,NDBI_800,NDBI_850,NDBI_900,NDBI_950,NDBI_1000
0,-73.971665,40.788763,2,4,8,13,14,24,26,38,...,-0.013411,-0.022313,-0.030077,-0.038276,-0.048054,-0.057627,-0.064880,-0.070877,-0.076302,-0.080141
1,-73.971928,40.788875,2,5,6,9,15,21,34,36,...,-0.008250,-0.019469,-0.028554,-0.036309,-0.045339,-0.054397,-0.061865,-0.068354,-0.073772,-0.078733
2,-73.967080,40.789080,1,3,3,4,5,5,8,12,...,-0.098532,-0.098487,-0.097550,-0.097520,-0.100565,-0.106120,-0.109531,-0.112391,-0.113822,-0.114814
3,-73.972550,40.789082,2,5,6,11,16,23,30,39,...,-0.001769,-0.013147,-0.023052,-0.031462,-0.039962,-0.048880,-0.055788,-0.062316,-0.068673,-0.075499
4,-73.969697,40.787953,2,2,4,5,6,13,16,21,...,-0.058645,-0.062678,-0.069504,-0.076383,-0.079686,-0.081898,-0.085792,-0.090658,-0.093918,-0.095784

In [33]:
# Read the canopy height data frame applicable for the test data.

test_canopy_df = pd.read_csv("test_canopy_df.csv")
test_canopy_df.head()

   Longitude   Latitude  UHI Index  canopy_height
0 -73.971665  40.788763        NaN      19.078571
1 -73.971928  40.788875        NaN      19.078571
2 -73.967080  40.789080        NaN      30.473438
3 -73.972550  40.789082        NaN      19.078571
4 -73.969697  40.787953        NaN      19.078571

In [34]:
# Check the latitude and longitude columns between the data frames are the same.

long_isequal = test_file["Longitude"].equals(test_canopy_df["Longitude"])
print(long_isequal)
lat_isequal = test_file["Latitude"].equals(test_canopy_df["Latitude"])
print(lat_isequal)

True
True

In [35]:
val_focaldata_total["canopy_height"] = test_canopy_df["canopy_height"]
val_focaldata_total.head()

,Longitude,Latitude,building_count_50,building_count_100,building_count_150,building_count_200,building_count_250,building_count_300,building_count_350,building_count_400,...,NDBI_600,NDBI_650,NDBI_700,NDBI_750,NDBI_800,NDBI_850,NDBI_900,NDBI_950,NDBI_1000,canopy_height
0,-73.971665,40.788763,2,4,8,13,14,24,26,38,...,-0.022313,-0.030077,-0.038276,-0.048054,-0.057627,-0.064880,-0.070877,-0.076302,-0.080141,19.078571
1,-73.971928,40.788875,2,5,6,9,15,21,34,36,...,-0.019469,-0.028554,-0.036309,-0.045339,-0.054397,-0.061865,-0.068354,-0.073772,-0.078733,19.078571
2,-73.967080,40.789080,1,3,3,4,5,5,8,12,...,-0.098487,-0.097550,-0.097520,-0.100565,-0.106120,-0.109531,-0.112391,-0.113822,-0.114814,30.473438
3,-73.972550,40.789082,2,5,6,11,16,23,30,39,...,-0.013147,-0.023052,-0.031462,-0.039962,-0.048880,-0.055788,-0.062316,-0.068673,-0.075499,19.078571
4,-73.969697,40.787953,2,2,4,5,6,13,16,21,...,-0.062678,-0.069504,-0.076383,-0.079686,-0.081898,-0.085792,-0.090658,-0.093918,-0.095784,19.078571

In [36]:
# Make a copy of val_focaldata_total for modelling purposes and drop the Latitude and Longitude columns.

submission_val_data = val_focaldata_total.copy()
submission_val_data = submission_val_data.drop(['Longitude', 'Latitude'], axis=1)
submission_val_data.head()

,building_count_50,building_count_100,building_count_150,building_count_200,building_count_250,building_count_300,building_count_350,building_count_400,building_count_450,building_count_500,...,NDBI_600,NDBI_650,NDBI_700,NDBI_750,NDBI_800,NDBI_850,NDBI_900,NDBI_950,NDBI_1000,canopy_height
0,2,4,8,13,14,24,26,38,44,49,...,-0.022313,-0.030077,-0.038276,-0.048054,-0.057627,-0.064880,-0.070877,-0.076302,-0.080141,19.078571
1,2,5,6,9,15,21,34,36,47,50,...,-0.019469,-0.028554,-0.036309,-0.045339,-0.054397,-0.061865,-0.068354,-0.073772,-0.078733,19.078571
2,1,3,3,4,5,5,8,12,18,26,...,-0.098487,-0.097550,-0.097520,-0.100565,-0.106120,-0.109531,-0.112391,-0.113822,-0.114814,30.473438
3,2,5,6,11,16,23,30,39,43,55,...,-0.013147,-0.023052,-0.031462,-0.039962,-0.048880,-0.055788,-0.062316,-0.068673,-0.075499,19.078571
4,2,2,4,5,6,13,16,21,26,33,...,-0.062678,-0.069504,-0.076383,-0.079686,-0.081898,-0.085792,-0.090658,-0.093918,-0.095784,19.078571

In [37]:
# Feature Scaling 

submission_val_data = submission_val_data.values
transformed_submission_data = sc.transform(submission_val_data)

In [38]:
# Making predictions

final_predictions = model.predict(transformed_submission_data)
final_prediction_series = pd.Series(final_predictions)

In [39]:
# Combining the results into dataframe

submission_df = pd.DataFrame({'Longitude':test_file['Longitude'].values, 'Latitude':test_file['Latitude'].values, 'UHI Index':final_prediction_series.values})

In [40]:
# Displaying the sample submission dataframe and viewing its stats

submission_df.head(10)
print(submission_df.describe(include="all"))

         Longitude     Latitude    UHI Index
count  1040.000000  1040.000000  1040.000000
mean    -73.934816    40.807991     0.999955
std       0.028661     0.023200     0.015320
min     -73.993163    40.758877     0.959308
25%     -73.957030    40.790802     0.989919
50%     -73.934618    40.809553     0.999770
75%     -73.910655    40.823054     1.010896
max     -73.879537    40.859243     1.039128

In [41]:
#Dumping the predictions into a csv file.

submission_df.to_csv("submission_final3.csv",index = False)